FROM nodered/node-red:latest-minimal
USER root

WORKDIR /usr/src/node-red

COPY /data/settings.js /data/settings.js
COPY /data/flows_cred.json /data/flows_cred.json
COPY /data/flows.json /data/flows.json
